### ISSUE TITLE
Installing and running IReS

### ISSUE THREAD

**Issue by rigaux** [project-asap/IReS-Platform#14]
Hi,

I just tried to make a local installation. I cloned the GitHub repo, defined the IRES_HOME env. var, run install.sh, giving the YARN_HOME when requested.
So far, ok. Then, when I start the server, I get:

./install.sh -r start
IReS-Platfrom home folder is /Users/philippe/IRES/IReS-Platform
start-ing ASAP server
/Users/philippe/IRES/IReS-Platform/asap-platform/asap-server/src/main/scripts/asap-server: line 24: cd: /Users/npapa/Documents/workspaceASAP/IReS-Platform/asap-platform/asap-server/target: No such file or directory

So, there is some harcoded path somewhere. I have a Mac Book. I' like to stabilize the installation process before asking my team to try again on the cluster.

Thx

Philippe

**Comment by gsvic** [comment]
Hi Phillipe,

Due to an issue related to the sed command, several issues may occur during the installation in a Mac Book. Such errors occurs because an Ubuntu-based OS provides a GNU sed while the OS X provides a BSD sed. Check this related topic in StackOverflow: http://stackoverflow.com/questions/16745988/sed-command-works-fine-on-ubuntu-but-not-mac

Finally we made some changes (see commit https://github.com/project-asap/IReS-Platform/commit/6723ae1f8ec2f9ca0a2cda337c954c56d69ef868) in order to make the script work in both systems. We tested it both in a Mac Book and an Ubuntu Server and everything works well.

Please try to install IReS again as follows:
1. `git clone git@github.com:project-asap/IReS-Platform.git`
2. `cd IReS-Platform`
3. `./install.sh`
4 `./install.sh -r start`

Best,
Victor

**Comment by rigaux** [comment]
Yes, it works! Bravo.

Ok, let's try now on our Debian cluster.

Many thanks

**Comment by rigaux** [comment]
Solved.
