### ISSUE TITLE
Error 500 when running a workflow

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/IReS-Platform#18]
Hi,

We cloned the last IRES version. Trying to run the Hello world script to check that everything is OK, we get the following error:

Problem accessing /web/workflows/execute. Reason:

    com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException

The console shows a message "1!!!!!!" 

Stan.

**Comment by Stan-imr** [comment]
After some investigations, it appears that the HelloWorld example contains hard-codded paths in the lua script.

/opt/asap-server/asapLibrary/operators/HelloWorld/HelloWorld.sh

**Comment by gsvic** [comment]
This probably happens because you are running the HelloWorld operator from the asapLibrary folder. The operators inside the defaultAsapLibrary folder (which is actually copied when you build the project with Maven) does not contain such hardcoded paths.

Concerning the "1!!!!!!" is just some `println` that we used during debugging. It will be removed soon.

**Comment by Stan-imr** [comment]
OK, the current doc is misleading about this. Thx.
