### ISSUE TITLE
Error 500 when changing a graph

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/IReS-Platform#19]
Adding a single line

crawlDocuments.helloWorld.0

and changing the graph results in the following error:

Problem accessing /web/abstractWorkflows/changeGraph. Reason:    java.lang.ArrayIndexOutOfBoundsException: 1

**Comment by gsvic** [comment]
The error occurs because you need to put commas instead of dots. 

Actually an edge definition should be something like "`crawlDocuments, helloWorld, 0`", which defines that the `crawlDocuments` dataset is the first (`0`) input to the `helloWorld` operator.

Check out this section at the docs: http://cognito.cslab.ece.ntua.gr/ires_docs/implementation.html#abstract-workflow-description

**Comment by Stan-imr** [comment]
The doc uses commas to separate the parameters.

**Comment by gsvic** [comment]
Could you send me a link to point me in this part of the docs?

**Comment by Stan-imr** [comment]
Just look at the links that you mention

An abstract workflow is defined as a DAG graph that connects a mixture of abstract and materialized datasets and operators. The missing information needed for describing the DAG graph is a set of edges. For example the description of the previous workflow can be created using the following list of edges (d1 is the output of TF_IDF and d2 is the output of k-Means).

crawlDocuments,TF_IDF,0
TF_IDF,d1,0
d1,k-Means,0
k-Means,d2,0
d2,$$target

**Comment by gsvic** [comment]
Yes, you are right, sorry about that. I have just updated my answer.

**Comment by Stan-imr** [comment]
Sure, no pb. Thanks for the hard work.
