### ISSUE TITLE
Where to put operators and workflows

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/IReS-Platform#21]
Trying to follow the doc with the LineCount example. No success. Looking at the IRES_HOME content, I can find many places for operators, datasets and workflows:
 
  - ./asap-platform/asap-server/asapLibrary/
  - ./asap-platform/asap-server/defaultAsapLibrary/abstractOperators
 - ./asap-platform/asap-server/target/asapLibrary/

It seems that the last one is used by the UI. The documentation mentions the 'asapLibrary", without referring to its parent dir.

Stan

**Comment by gsvic** [comment]
The asapLibrary folder which the running system can see is placed in the target directory (target/asapLibrary).

The defaultAsapLibrary is the default asapLibrary directory that is being copied into the target folder every time the project is being compiled via maven (`mvn install`, `mvn package`, etc). We maintain two different folders(defaultAsapLibrary and asapLibrary) in order to prevent new users of runtime errors which will probably occur when the server starts.

The asapLibrary folder contains some workflow/operator implementations we made in our cluster. One can see them as example templates but they need some modifications in order to run in another cluster.

**Comment by Stan-imr** [comment]
To be clarified in the doc.
