### ISSUE TITLE
Lua script is not updated if the user re-uploads the operator over API

### ISSUE THREAD

**Issue by project-asap** [project-asap/IReS-Platform#9]
If the user uploads an operator using the respective API call:
POST /operators/addTarball
the lua script is created as expected.

If the user changes something in the description of the operator
e.g. Execution.memory=8192
creates a new tarball and uploads it again with the same name
the memory is not updated in the lua file.

If the user deletes completely the operator from:
IRes-Platform/asap-platform/asap-server-target/asapLibrary/operators
and uploads the last created tarball
the memory in the lua file will be correctly set to 8192.

**Comment by gsvic** [comment]
When an operator is being added via the REST API the .lua file is generated only if it does not exists. The functionality can be seen in this [line](https://github.com/project-asap/IReS-Platform/commit/0573f56f14a8efa6a24177f7fcc636c11e4fca47#diff-fdd9906504fa21e3b1a8ee101f389ae0R262).

So, in order to generate a new .lua file the old one should be deleted.
